#! TO DO:
#! add a rule to build the report
all: report.html

#! TO DO:
#! add a rule to create the output of 
#! code/01_make_output1.R
output1/random_numbers1:
	Rscript code/01_make_output1.R

#! TO DO:
#! add a rule to create the output of 
#! code/02_make_output2.R
output2/random_numbers2:
	Rscript code/02_make_output2.R

#! TO DO:
#! add a rule to create the output of 
#! code/03_make_output3.R
output3/random_numbers3:
	Rscript code/03_make_output3.R

#! TO DO:
#! add a PHONY target for removing .rds files
#! from the output1/2/3 directories

rm -f output1/*.rds output2/*.rds output3/*.rds report.html